"""The changelogs' history, generated once, and git-cliff retired.

See stackr's RFC-0003, Releases and versioning.

release-please writes each package's changelog from here on, from the import. Before it does,
git-cliff writes each package's history once more (changelogs.py); then every cliff.toml, the
changelog targets and git-cliff itself go.
"""

from pathlib import Path

from changelogs import generate
from lib import PACKAGES, install, remove, replace, run

for name in PACKAGES:
    generate(name, Path(f"packages/{name}/CHANGELOG.md"))
    remove(f"packages/{name}/cliff.toml")

for name in ("artifactr", "reflexr", "evalr", "relayr"):
    replace(f"packages/{name}/pyproject.toml", '    "git-cliff>=2.14",\n', "")
replace("packages/stackr/pyproject.toml", '  "git-cliff>=2.14.2",\n', "")
run("uv", "lock", "--quiet")

makefile = "packages/stackr/Makefile"
replace(makefile, " docs-reference changelog clean\n", " docs-reference clean\n")
replace(
    makefile,
    "changelog: ## Regenerate CHANGELOG.md from conventional commits\n"
    "\t$(UV) run git-cliff --output CHANGELOG.md\n"
    "\t@$(UV) run python -c \"import pathlib; p = pathlib.Path('CHANGELOG.md'); "
    "p.write_text(p.read_text().rstrip() + '\\n')\"\n\n",
    "",
)
run(
    "uv",
    "run",
    "--quiet",
    "--no-project",
    "--with",
    "pyyaml",
    "python",
    "scripts/docs-reference",
    cwd="packages/stackr",
)

PAGE = "<!-- This page includes the package's CHANGELOG.md, which release-please updates with every release. -->\n"
for name in ("artifactr", "reflexr"):
    replace(
        f"docs/{name}/project/changelog.md",
        "<!-- This page includes the repository's CHANGELOG.md, generated by `make changelog`. -->\n",
        PAGE,
    )
replace(
    "docs/evalr/project/changelog.md",
    "<!-- This page includes the repository's CHANGELOG.md, which `make docs` regenerates. -->\n",
    PAGE,
)
replace(
    "docs/stackr/project/changelog.md",
    "<!--\n"
    "This page includes the repository's CHANGELOG.md, which git-cliff generates from the commit\n"
    "history: `make changelog`, and again before every build of the site, so the site shows main's.\n"
    "-->\n",
    PAGE,
)

# relayr's history has its first changelog, and its section a page for it.
install()
replace(
    "docs/relayr/.nav.yml",
    "- Brand: assets/brand/README.md\n",
    "- Changelog: project/changelog.md\n- Brand: assets/brand/README.md\n",
)
